# Generated by Django 5.1.3 on 2024-12-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adrenalife', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
