# Generated by Django 5.1.3 on 2024-12-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adrenalife', '0002_usuarios_data_nascimento_usuarios_senha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
