# Generated by Django 5.1.4 on 2025-02-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adrenalife', '0003_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=255)),
                ('descricao', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='categoria_atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('vagas_disponiveis', models.IntegerField()),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
