# Generated by Django 5.1.4 on 2025-02-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adrenalife', '0004_atividade_categoria_atividade_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_atividade',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
