# Generated by Django 5.1.4 on 2025-02-24 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adrenalife', '0006_atividade_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_adrenalife.categoria_atividade'),
        ),
    ]
