# Generated by Django 5.1.4 on 2025-02-25 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adrenalife', '0007_alter_atividade_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='atividade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_adrenalife.atividade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='nome',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adrenalife.categoria_atividade'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateField(),
        ),
    ]
