# Generated by Django 5.1.4 on 2025-02-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adrenalife', '0008_evento_atividade_evento_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
