# Generated by Django 5.1.3 on 2025-02-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adrenalife', '0010_alter_evento_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('funcionario', 'Funcionário')], default='cliente', max_length=11),
        ),
    ]
