# Generated by Django 5.1.3 on 2025-02-26 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adrenalife', '0011_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='meio',
        ),
    ]
