# Generated by Django 5.1.3 on 2025-02-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adrenalife', '0012_remove_usuario_meio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
