# Generated by Django 5.1.3 on 2025-02-27 18:17

import app_adrenalife.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adrenalife', '0013_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(max_length=255, validators=[app_adrenalife.models.validar_cidade]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[app_adrenalife.models.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(validators=[app_adrenalife.models.validar_data_nascimento]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, validators=[app_adrenalife.models.validar_email]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=255, validators=[app_adrenalife.models.validar_nome]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=11, validators=[app_adrenalife.models.validar_telefone]),
        ),
    ]
