# Generated by Django 5.1.3 on 2025-02-28 03:24

import app_adrenalife.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adrenalife', '0014_alter_usuario_cidade_alter_usuario_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=254, validators=[app_adrenalife.models.validar_email]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=15, validators=[app_adrenalife.models.validar_telefone]),
        ),
    ]
