# Generated by Django 5.1.4 on 2025-02-28 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adrenalife', '0014_alter_usuario_cidade_alter_usuario_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adrenalife.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adrenalife.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'evento')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='eventos_inscritos',
            field=models.ManyToManyField(through='app_adrenalife.InscricaoEvento', to='app_adrenalife.evento'),
        ),
    ]
