# Generated by Django 5.1.3 on 2025-02-28 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adrenalife', '0015_alter_usuario_email_alter_usuario_telefone'),
        ('app_adrenalife', '0015_inscricaoevento_usuario_eventos_inscritos'),
    ]

    operations = [
    ]
